FROM node:20-alpine AS builder

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

FROM node:20-alpine

RUN apk add --no-cache netcat-openbsd

WORKDIR /app

COPY wait-for-mysql.sh /wait-for-mysql.sh
RUN chmod +x /wait-for-mysql.sh

COPY --from=builder /app/node_modules /app/node_modules

COPY . .

RUN npm install -g nodemon

CMD ["/wait-for-mysql.sh", "db-api.cef2gw4amtq1.us-east-1.rds.amazonaws.com", "3306", "npm", "run", "dev"]