version: '3.9'

services:
  mysqldb:
    image: mysql
    restart: always
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    depends_on:
      - mysqldb
    volumes:
      - .:/app                
      - /app/node_modules    
    environment:
      - NODE_ENV=development
    networks:
      - mynetwork

volumes:
  mysql-data:

networks:
  mynetwork: